spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jobapp?serverTimezone=Asia/Seoul
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
